#!/bin/bash

# Tenant Admin Service Startup Script
# This script sets up environment variables and starts the Tenant Admin Service

echo "Starting Tenant Admin Service..."

# Set required environment variables
export ENVIRONMENT="development"
export SERVICE_NAME="tenant-admin-service"
export SERVICE_VERSION="1.0.0"
export SERVICE_DESCRIPTION="Tenant Admin Service for Tenant-Specific Administration"
export LOG_LEVEL="info"
export LOG_FORMAT="json"

# Server configuration
export SERVER_HOST="0.0.0.0"
export SERVER_PORT=8099
export SERVER_READ_TIMEOUT=30
export SERVER_WRITE_TIMEOUT=30
export SERVER_IDLE_TIMEOUT=120

# Database configuration
export DB_HOST="localhost"
export DB_PORT=5432
export DB_USER="postgres"
export DB_PASSWORD="postgres"
export DB_NAME="statuspage_tenant_admin"
export DB_SSL_MODE="disable"
export DB_MAX_CONNS=100
export DB_MIN_CONNS=10
export DB_MAX_IDLE=10
export DB_MAX_LIFETIME=3600

# Tenant configuration
export TENANT_DEFAULT_PLAN="free"
export TENANT_AVAILABLE_PLANS="free,pro,enterprise"
export TENANT_MAX_USERS_PER_TENANT=10
export TENANT_MAX_SERVICES_PER_TENANT=25
export TENANT_MAX_MONITORS_PER_TENANT=100
export TENANT_MAX_SUBSCRIBERS_PER_TENANT=1000
export TENANT_MAX_INCIDENTS_PER_TENANT=100
export TENANT_MAX_MAINTENANCE_PER_TENANT=50
export TENANT_CUSTOM_DOMAIN_ENABLED=true
export TENANT_WHITE_LABEL_ENABLED=false
export TENANT_API_ENABLED=true
export TENANT_INTEGRATIONS_ENABLED=true
export TENANT_ANALYTICS_ENABLED=true
export TENANT_SUPPORT_LEVEL="email"
export TENANT_FEATURE_FLAGS_ENABLED=true
export TENANT_AUDIT_LOGGING_ENABLED=true
export TENANT_BACKUP_ENABLED=true
export TENANT_BACKUP_INTERVAL=24
export TENANT_RETENTION_DAYS=365

# Optional: Load from config file
# export CONFIG_FILE="/path/to/config.json"

echo "Environment variables set:"
echo "  SERVICE_NAME: $SERVICE_NAME"
echo "  SERVICE_VERSION: $SERVICE_VERSION"
echo "  SERVER_PORT: $SERVER_PORT"
echo "  DB_HOST: $DB_HOST"
echo "  DB_PORT: $DB_PORT"
echo "  DB_NAME: $DB_NAME"
echo "  TENANT_DEFAULT_PLAN: $TENANT_DEFAULT_PLAN"
echo "  TENANT_AVAILABLE_PLANS: $TENANT_AVAILABLE_PLANS"
echo "  TENANT_MAX_USERS_PER_TENANT: $TENANT_MAX_USERS_PER_TENANT"
echo "  TENANT_MAX_SERVICES_PER_TENANT: $TENANT_MAX_SERVICES_PER_TENANT"
echo "  TENANT_MAX_MONITORS_PER_TENANT: $TENANT_MAX_MONITORS_PER_TENANT"
echo "  TENANT_MAX_SUBSCRIBERS_PER_TENANT: $TENANT_MAX_SUBSCRIBERS_PER_TENANT"
echo "  TENANT_MAX_INCIDENTS_PER_TENANT: $TENANT_MAX_INCIDENTS_PER_TENANT"
echo "  TENANT_MAX_MAINTENANCE_PER_TENANT: $TENANT_MAX_MAINTENANCE_PER_TENANT"
echo "  TENANT_CUSTOM_DOMAIN_ENABLED: $TENANT_CUSTOM_DOMAIN_ENABLED"
echo "  TENANT_WHITE_LABEL_ENABLED: $TENANT_WHITE_LABLED_ENABLED"
echo "  TENANT_API_ENABLED: $TENANT_API_ENABLED"
echo "  TENANT_INTEGRATIONS_ENABLED: $TENANT_INTEGRATIONS_ENABLED"
echo "  TENANT_ANALYTICS_ENABLED: $TENANT_ANALYTICS_ENABLED"
echo "  TENANT_SUPPORT_LEVEL: $TENANT_SUPPORT_LEVEL"
echo "  TENANT_FEATURE_FLAGS_ENABLED: $TENANT_FEATURE_FLAGS_ENABLED"
echo "  TENANT_AUDIT_LOGGING_ENABLED: $TENANT_AUDIT_LOGGING_ENABLED"
echo "  TENANT_BACKUP_ENABLED: $TENANT_BACKUP_ENABLED"
echo "  TENANT_BACKUP_INTERVAL: $TENANT_BACKUP_INTERVAL"
echo "  TENANT_RETENTION_DAYS: $TENANT_RETENTION_DAYS"

# Start the service
echo "Starting Tenant Admin Service on port $SERVER_PORT..."
go run cmd/main.go

