###############################
# MockServer Properties
###############################

# Enable CORS
mockserver.enableCORSForAllResponses=true

# Log level
mockserver.logLevel=INFO

# Maximum timeout
mockserver.maxTimeout=120000

# Request log size
mockserver.maxLogEntries=1000
