# Atlas configuration for incident-service
# Generated by: scripts/generate-atlas-config.sh
#
# This configuration uses GORM models as the source of truth for database schema.
# Migrations are generated using: atlas migrate diff --env dev
# Migrations are applied using: atlas migrate apply --env dev
#
# SAFETY FEATURES:
# - Migration state tracked in atlas_schema_revisions table
# - Prevents accidental re-application of migrations
# - Linear migration application enforced
# - Rollback support via atlas migrate down

# GORM models as schema source
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "ariga.io/atlas-provider-gorm",
    "load",
    "--path", "./internal/models",
    "--dialect", "postgres",
  ]
}

# Development environment (localhost PostgreSQL)
env "dev" {
  src = data.external_schema.gorm.url
  url = "postgres://postgres:postgres@localhost:5432/statuspage_incident?sslmode=disable"
  dev = "docker://postgres/14/dev?search_path=public"

  migration {
    dir = "file://migrations"
    # Track migration state to prevent accidental re-runs
    revisions_schema = "atlas_schema_revisions"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }

  # Safety: Require manual approval for destructive changes in dev
  diff {
    skip {
      drop_schema = true
      drop_table  = true
    }
  }
}

# Docker environment (for containerized development)
env "docker" {
  src = data.external_schema.gorm.url
  url = "postgres://postgres:postgres@statuspage-postgres:5432/statuspage_incident?sslmode=disable"
  dev = "docker://postgres/14/dev?search_path=public"

  migration {
    dir = "file://migrations"
    revisions_schema = "atlas_schema_revisions"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

# Production environment (RDS or managed PostgreSQL)
env "prod" {
  src = data.external_schema.gorm.url

  # MUST be set via environment variable for security
  # Example: export ATLAS_URL="postgres://user:pass@rds-endpoint:5432/statuspage_incident?sslmode=require"
  url = getenv("ATLAS_URL")

  migration {
    dir = "file://migrations"
    revisions_schema = "atlas_schema_revisions"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }

  # CRITICAL: Prevent accidental destructive changes in production
  diff {
    skip {
      drop_schema = true
      drop_table  = true
      drop_column = true
    }
  }

  # Require baseline before first migration
  migrate {
    baseline = getenv("ATLAS_BASELINE")
  }
}
