#!/bin/bash
#
# Generate Atlas configuration for a microservice
# Usage: ./generate-atlas-config.sh <service-name> <database-name>
#
# This script creates a standardized atlas.hcl configuration that:
# - Uses GORM models as the source of truth
# - Generates migrations from Go models
# - Tracks migration state (prevents accidental re-runs)
# - Supports dev and prod environments
#

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <service-name> <database-name>"
    echo "Example: $0 user-service statuspage_user"
    exit 1
fi

SERVICE_NAME=$1
DB_NAME=$2
SERVICE_DIR="./microservices/$SERVICE_NAME"

# Validate service directory exists
if [ ! -d "$SERVICE_DIR" ]; then
    echo "Error: Service directory not found: $SERVICE_DIR"
    exit 1
fi

# Validate models directory exists
if [ ! -d "$SERVICE_DIR/internal/models" ]; then
    echo "Warning: Models directory not found: $SERVICE_DIR/internal/models"
    echo "Creating models directory..."
    mkdir -p "$SERVICE_DIR/internal/models"
fi

# Create migrations directory if it doesn't exist
if [ ! -d "$SERVICE_DIR/migrations" ]; then
    echo "Creating migrations directory..."
    mkdir -p "$SERVICE_DIR/migrations"
fi

# Generate atlas.hcl
cat > "$SERVICE_DIR/atlas.hcl" << EOF
# Atlas configuration for ${SERVICE_NAME}
# Generated by: scripts/generate-atlas-config.sh
#
# This configuration uses GORM models as the source of truth for database schema.
# Migrations are generated using: atlas migrate diff --env dev
# Migrations are applied using: atlas migrate apply --env dev
#
# SAFETY FEATURES:
# - Migration state tracked in atlas_schema_revisions table
# - Prevents accidental re-application of migrations
# - Linear migration application enforced
# - Rollback support via atlas migrate down

# GORM models as schema source
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "ariga.io/atlas-provider-gorm",
    "load",
    "--path", "./internal/models",
    "--dialect", "postgres",
  ]
}

# Development environment (localhost PostgreSQL)
env "dev" {
  src = data.external_schema.gorm.url
  url = "postgres://postgres:postgres@localhost:5432/${DB_NAME}?sslmode=disable"
  dev = "docker://postgres/14/dev?search_path=public"

  migration {
    dir = "file://migrations"
    # Track migration state to prevent accidental re-runs
    revisions_schema = "atlas_schema_revisions"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }

  # Safety: Require manual approval for destructive changes in dev
  diff {
    skip {
      drop_schema = true
      drop_table  = true
    }
  }
}

# Docker environment (for containerized development)
env "docker" {
  src = data.external_schema.gorm.url
  url = "postgres://postgres:postgres@statuspage-postgres:5432/${DB_NAME}?sslmode=disable"
  dev = "docker://postgres/14/dev?search_path=public"

  migration {
    dir = "file://migrations"
    revisions_schema = "atlas_schema_revisions"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

# Production environment (RDS or managed PostgreSQL)
env "prod" {
  src = data.external_schema.gorm.url

  # MUST be set via environment variable for security
  # Example: export ATLAS_URL="postgres://user:pass@rds-endpoint:5432/${DB_NAME}?sslmode=require"
  url = getenv("ATLAS_URL")

  migration {
    dir = "file://migrations"
    revisions_schema = "atlas_schema_revisions"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }

  # CRITICAL: Prevent accidental destructive changes in production
  diff {
    skip {
      drop_schema = true
      drop_table  = true
      drop_column = true
    }
  }

  # Require baseline before first migration
  migrate {
    baseline = getenv("ATLAS_BASELINE")
  }
}
EOF

echo "✓ Generated atlas.hcl for $SERVICE_NAME"
echo "  Database: $DB_NAME"
echo "  Location: $SERVICE_DIR/atlas.hcl"
echo ""
echo "Next steps:"
echo "  1. Ensure models exist in $SERVICE_DIR/internal/models/"
echo "  2. Generate migration: cd $SERVICE_DIR && atlas migrate diff initial_schema --env dev"
echo "  3. Apply migration: atlas migrate apply --env dev"
